### ISSUE TITLE
Exception in TerraFX.Samples coming from D3D12GraphicsHeap

### ISSUE THREAD

**Issue by carlossanlop** [terrafx/terrafx#84]
### Bug

I wanted to check out the project, so I cloned it, ran TerraFX.Samples (the default startup project) with Visual Studio, and I hit this exception:

```
Running: D3D12.EnumerateGraphicsAdapters
    Name: NVIDIA Quadro P400
        Device ID: 7347
        Vendor ID: 4318
    Name: Microsoft Basic Render Driver
        Device ID: 140
        Vendor ID: 5140
Running: Vulkan.EnumerateGraphicsAdapters
    Name: Quadro P400
        Device ID: 7347
        Vendor ID: 4318
Running: D3D12.HelloWindow
Running: Vulkan.HelloWindow
Running: D3D12.HelloTriangle
Unhandled exception. System.Runtime.InteropServices.ExternalException (0x80070057): CreateHeap failed with an error code of -2147024809
   at TerraFX.Utilities.ExceptionUtilities.ThrowExternalException(String methodName, Int32 errorCode) in D:\terrafx\sources\Utilities\ExceptionUtilities.cs:line 48
   at TerraFX.Graphics.Providers.D3D12.HelperUtilities.ThrowExternalExceptionIfFailed(String methodName, Int32 hr) in D:\terrafx\sources\Providers\Graphics\D3D12\HelperUtilities.cs:line 28
   at TerraFX.Graphics.Providers.D3D12.D3D12GraphicsHeap.CreateD3D12Heap() in D:\terrafx\sources\Providers\Graphics\D3D12\D3D12GraphicsHeap.cs:line 101
   at TerraFX.Utilities.ValueLazy`1.CreateValue() in D:\terrafx\sources\Utilities\ValueLazy`1.cs:line 119
   at TerraFX.Utilities.ValueLazy`1.get_Value() in D:\terrafx\sources\Utilities\ValueLazy`1.cs:line 64
   at TerraFX.Graphics.Providers.D3D12.D3D12GraphicsHeap.get_D3D12Heap() in D:\terrafx\sources\Providers\Graphics\D3D12\D3D12GraphicsHeap.cs:line 39
   at TerraFX.Graphics.Providers.D3D12.D3D12GraphicsBuffer.CreateD3D12Resource() in D:\terrafx\sources\Providers\Graphics\D3D12\D3D12GraphicsBuffer.cs:line 95
   at TerraFX.Utilities.ValueLazy`1.CreateValue() in D:\terrafx\sources\Utilities\ValueLazy`1.cs:line 119
   at TerraFX.Utilities.ValueLazy`1.get_Value() in D:\terrafx\sources\Utilities\ValueLazy`1.cs:line 64
   at TerraFX.Graphics.Providers.D3D12.D3D12GraphicsBuffer.get_D3D12Resource() in D:\terrafx\sources\Providers\Graphics\D3D12\D3D12GraphicsBuffer.cs:line 41
   at TerraFX.Graphics.Providers.D3D12.D3D12GraphicsBuffer.Map[T](UIntPtr readRangeOffset, UIntPtr readRangeLength) in D:\terrafx\sources\Providers\Graphics\D3D12\D3D12GraphicsBuffer.cs:line 56
   at TerraFX.Graphics.GraphicsBuffer.Map[T]() in D:\terrafx\sources\Graphics\GraphicsBuffer.cs:line 62
   at TerraFX.Samples.Graphics.HelloTriangle.<CreateTrianglePrimitive>g__CreateVertexBuffer|9_0(GraphicsContext graphicsContext, GraphicsHeap graphicsHeap, GraphicsBuffer vertexStagingBuffer, Single aspectRatio) in D:\terrafx\samples\TerraFX\Graphics\HelloTriangle.cs:line 110
   at TerraFX.Samples.Graphics.HelloTriangle.CreateTrianglePrimitive(GraphicsContext graphicsContext, GraphicsBuffer vertexStagingBuffer) in D:\terrafx\samples\TerraFX\Graphics\HelloTriangle.cs:line 103
   at TerraFX.Samples.Graphics.HelloTriangle.Initialize(Application application) in D:\terrafx\samples\TerraFX\Graphics\HelloTriangle.cs:line 59
   at TerraFX.Samples.Program.Run(Sample sample) in D:\terrafx\samples\TerraFX\Program.cs:line 108
   at TerraFX.Samples.Program.<>c__DisplayClass10_0.<RunSample>b__0() in D:\terrafx\samples\TerraFX\Program.cs:line 152
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

D:\terrafx\artifacts\bin\samples\TerraFX.Samples\Debug\net5.0\TerraFX.Samples.exe (process 12488) exited with code 0.
```
#### Description (optional)
Failure happened here:
https://github.com/terrafx/terrafx/blob/c72075414abda58e112b58fa576c3c7664bdf45a/sources/Providers/Graphics/D3D12/D3D12GraphicsHeap.cs#L101-L105

I'm sure I'm missing something, maybe misconfiguration, or the project is running something incompatible with my machine.

This is my work PC with Windows 10 64 bits.

**Comment by john-h-k** [comment]
It's 2am and I've only looked a bit but I suspect it's a case of not having tier 2 merged heap support, and the heap not being properly setup for tier 1 split heap with the appropriate flags

**Comment by tannergooding** [comment]
@john-h-k, that's my expectation as well.

It's something I'm hoping to fix with the memory allocator work I'm hoping to finish 😄 

At the very least, I can detect and error on this case for now....

**Comment by tannergooding** [comment]
@carlossanlop, could you try https://github.com/terrafx/terrafx/pull/85 and see if it now tells you "TerraFX requires Resource Heap Tier 2"?

**Comment by carlossanlop** [comment]
@tannergooding yes, I got that exception now:

```
Running: D3D12.EnumerateGraphicsAdapters
    Name: NVIDIA Quadro P400
        Device ID: 7347
        Vendor ID: 4318
    Name: Microsoft Basic Render Driver
        Device ID: 140
        Vendor ID: 5140
Running: Vulkan.EnumerateGraphicsAdapters
    Name: Quadro P400
        Device ID: 7347
        Vendor ID: 4318
Running: D3D12.HelloWindow
Unhandled exception. System.NotSupportedException: TerraFX currently requires a device that supports Resource Heap Tier 2
   at TerraFX.Graphics.Providers.D3D12.D3D12GraphicsDevice.CreateD3D12Device() in D:\terrafx\sources\Providers\Graphics\D3D12\D3D12GraphicsDevice.cs:line 246
   at TerraFX.Utilities.ValueLazy`1.CreateValue() in D:\terrafx\sources\Utilities\ValueLazy`1.cs:line 119
   at TerraFX.Utilities.ValueLazy`1.get_Value() in D:\terrafx\sources\Utilities\ValueLazy`1.cs:line 64
   at TerraFX.Graphics.Providers.D3D12.D3D12GraphicsDevice.get_D3D12Device() in D:\terrafx\sources\Providers\Graphics\D3D12\D3D12GraphicsDevice.cs:line 86
   at TerraFX.Graphics.Providers.D3D12.D3D12GraphicsFence.CreateD3D12Fence() in D:\terrafx\sources\Providers\Graphics\D3D12\D3D12GraphicsFence.cs:line 126
   at TerraFX.Utilities.ValueLazy`1.CreateValue() in D:\terrafx\sources\Utilities\ValueLazy`1.cs:line 119
   at TerraFX.Utilities.ValueLazy`1.get_Value() in D:\terrafx\sources\Utilities\ValueLazy`1.cs:line 64
   at TerraFX.Graphics.Providers.D3D12.D3D12GraphicsFence.get_D3D12Fence() in D:\terrafx\sources\Providers\Graphics\D3D12\D3D12GraphicsFence.cs:line 42
   at TerraFX.Graphics.Providers.D3D12.D3D12GraphicsFence.get_IsSignalled() in D:\terrafx\sources\Providers\Graphics\D3D12\D3D12GraphicsFence.cs:line 56
   at TerraFX.Graphics.Providers.D3D12.D3D12GraphicsFence.Reset() in D:\terrafx\sources\Providers\Graphics\D3D12\D3D12GraphicsFence.cs:line 61
   at TerraFX.Graphics.Providers.D3D12.D3D12GraphicsDevice..ctor(D3D12GraphicsAdapter graphicsAdapter, IGraphicsSurface graphicsSurface, Int32 graphicsContextCount) in D:\terrafx\sources\Providers\Graphics\D3D12\D3D12GraphicsDevice.cs:line 55
   at TerraFX.Graphics.Providers.D3D12.D3D12GraphicsAdapter.CreateD3D12GraphicsDevice(IGraphicsSurface graphicsSurface, Int32 graphicsContextCount) in D:\terrafx\sources\Providers\Graphics\D3D12\D3D12GraphicsAdapter.cs:line 75
   at TerraFX.Graphics.Providers.D3D12.D3D12GraphicsAdapter.CreateGraphicsDevice(IGraphicsSurface graphicsSurface, Int32 graphicsContextCount) in D:\terrafx\sources\Providers\Graphics\D3D12\D3D12GraphicsAdapter.cs:line 79
   at TerraFX.Samples.Graphics.HelloWindow.Initialize(Application application) in D:\terrafx\samples\TerraFX\Graphics\HelloWindow.cs:line 43
   at TerraFX.Samples.Program.Run(Sample sample) in D:\terrafx\samples\TerraFX\Program.cs:line 108
   at TerraFX.Samples.Program.<>c__DisplayClass10_0.<RunSample>b__0() in D:\terrafx\samples\TerraFX\Program.cs:line 152
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

D:\terrafx\artifacts\bin\samples\TerraFX.Samples\Debug\net5.0\TerraFX.Samples.exe (process 14848) exited with code 0.
```

**Comment by tannergooding** [comment]
Thanks for the confirmation!

Hopefully I can get the memory allocator work done and that will allow the samples to run on more devices!

**Comment by tannergooding** [comment]
This should be resolved now that the memory allocator has been updated: https://github.com/terrafx/terrafx/pull/91
